version: '3.9'

services:
  lp-frontend:
    image: lp-frontend
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
  lp-backend:
    image: lp-backend
    build: ./server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
