services:
  lp-frontend:
    image: lp-frontend
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://localhost:8000
    ports:
      - 3000:80
  lp-backend:
    image: lp-backend
    build: ./server
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    environment:
      PORT: "8000"
