import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { apiUrl } from "../../config/api";
import { SITE_URL, SITE_NAME } from "../../config/site";
import { fromSlug } from "../../util/slug";
import Seo from "../../seo/Seo";
import LoadingSpinner from "../LoadingSpinner/LoadingSpinner";

import "./LearningPathShare.scss";

function buildJsonLd(doc) {
  const url = `${SITE_URL}/lp/${doc.topicSlug}`;

  const steps = [];
  let stepIndex = 1;
  for (const sectionTitle of Object.keys(doc.completion)) {
    const items = doc.completion[sectionTitle];
    if (Array.isArray(items)) {
      for (const item of items) {
        steps.push({
          "@type": "HowToStep",
          position: stepIndex++,
          name: item,
          text: `${sectionTitle}: ${item}`,
        });
      }
    }
  }

  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
          {
            "@type": "ListItem",
            position: 2,
            name: `Learn ${doc.topic}`,
            item: url,
          },
        ],
      },
      {
        "@type": "HowTo",
        name: `Learning Path: ${doc.topic}`,
        description: `Step-by-step learning path for ${doc.topic} — beginner to advanced concepts generated by AI.`,
        url,
        step: steps,
      },
      {
        "@type": "WebPage",
        "@id": url,
        url,
        name: `Learn ${doc.topic} | ${SITE_NAME}`,
        datePublished: doc.createdAt,
        dateModified: doc.updatedAt,
        isPartOf: { "@id": `${SITE_URL}/#website` },
      },
    ],
  };
}

export default function LearningPathShare() {
  const { topicSlug } = useParams();
  const [doc, setDoc] = useState(null);
  const [error, setError] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    async function fetchSaved() {
      setIsLoading(true);
      setError(null);
      try {
        const res = await fetch(
          apiUrl(`/v1/lp_saved/${encodeURIComponent(topicSlug)}`),
        );
        if (!res.ok) {
          setError(res.status === 404 ? "not_found" : "server_error");
          return;
        }
        const data = await res.json();
        if (!cancelled) setDoc(data);
      } catch {
        if (!cancelled) setError("network_error");
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    }

    fetchSaved();
    return () => {
      cancelled = true;
    };
  }, [topicSlug]);

  const displayTopic = doc?.topic ?? fromSlug(topicSlug);

  if (isLoading) {
    return (
      <div className="lp-share-page">
        <Seo
          title={`Learn ${displayTopic}`}
          description={`Structured learning path for ${displayTopic}: beginner to advanced concepts.`}
          path={`/lp/${topicSlug}`}
        />
        <div className="lp-share-loading">
          <LoadingSpinner />
        </div>
      </div>
    );
  }

  if (error || !doc) {
    return (
      <div className="lp-share-page">
        <Seo title={`Learn ${displayTopic}`} path={`/lp/${topicSlug}`} noindex />
        <div style={{ height: "100px" }} />
        <h1>Learning path not found</h1>
        <p>
          No saved learning path exists for &ldquo;{displayTopic}&rdquo; yet.
        </p>
        <Link
          to={`/learningpath?term=${encodeURIComponent(displayTopic)}`}
          className="lp-share-generate-link"
        >
          Generate one now
        </Link>
      </div>
    );
  }

  return (
    <div className="lp-share-page">
      <Seo
        title={`Learn ${doc.topic}`}
        description={`Structured learning path for ${doc.topic}: beginner to advanced concepts generated by AI.`}
        path={`/lp/${doc.topicSlug}`}
        jsonLd={buildJsonLd(doc)}
      />

      <div style={{ height: "100px" }} />
      <main>
        <article>
          <header>
            <h1>
              Learning Path: <span className="gradient-text">{doc.topic}</span>
            </h1>
            <p className="lp-share-subtitle">
              A structured roadmap from beginner to advanced, generated by AI.
            </p>
          </header>

          {Object.entries(doc.completion).map(([level, items]) => (
            <section key={level} id={level.toLowerCase()} aria-labelledby={`heading-${level.toLowerCase()}`}>
              <h2 id={`heading-${level.toLowerCase()}`}>{level}</h2>
              <ol>
                {(Array.isArray(items) ? items : []).map((item, i) => (
                  <li key={`${level}-${i}`}>{item}</li>
                ))}
              </ol>
            </section>
          ))}

          <footer className="lp-share-footer">
            <Link
              to={`/learningpath?term=${encodeURIComponent(doc.topic)}`}
              className="lp-share-generate-link"
            >
              Regenerate this learning path
            </Link>
          </footer>
        </article>
      </main>
      <div style={{ height: "50px" }} />
    </div>
  );
}
