steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: server
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/lp-backend/${_SERVICE_NAME}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/lp-backend/${_SERVICE_NAME}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/lp-backend/${_SERVICE_NAME}"
      - "--region=${_REGION}"
      - "--platform=managed"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: lp-backend-staging
  _REGION: northamerica-northeast2

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/lp-backend/${_SERVICE_NAME}"
